#program to demonstrate the functionality of Arithematic Operators
a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
print("-"*50)
print("Arithmatic operator result:")
print("-"*50)
print("{}+{}={}".format(a,b,a+b))
print("{}-{}={}".format(a,b,a-b))
print("{}*{}={}".format(a,b,a*b))
print("{}/{}={}".format(a,b,a/b))
print("{}//{}={}".format(a,b,a//b))
print("{}%{}={}".format(a,b,a%b))
print("{}**{}={}".format(a,b,a**b))

print("-"*50)
