from tkinter import*
root=Tk()
frame=Frame(root)
button=Button(frame, text="Click here")
button.pack()
button2=Button(frame, text="Second click")
button.pack()
button3=Button(frame, text="Third button")
button.pack()
frame.pack()
root.mainloop()
